server:
  port: 8080


# Spring datasource configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/uniclub
    username: root
    password: linhth123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  private-key: 9RybnQtMuvICkezmmSfGpSd5xA7LiEtCklmoYtHh5P0=

path:
  save-file: C:\Users\Admin\Desktop\savefile
